import { useEffect, useState } from "react";
import { ArrowUpRight, CheckCircle2, Clock3, Package, ShoppingBag, Star, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import type { AdminDashboardResponse, Order, Product, Review } from "@shared/api";
import { adminApi } from "@/lib/admin-api";

const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat("fr-FR", { day: "2-digit", month: "short" }).format(new Date(value)) : "Date inconnue";
const money = (value?: number | null) => typeof value === "number" ? `${value.toFixed(2).replace(".", ",")} €` : "—";
const today = new Intl.DateTimeFormat("fr-FR", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date());
type DashboardData = AdminDashboardResponse & { fromCache?: boolean; cachedAt?: string };

function StatCard({ label, value, detail, icon: Icon, accent, to }: { label: string; value: string; detail: string; icon: typeof Package; accent: string; to: string }) {
  return <Link to={to} className="block rounded-2xl border border-[#dfe6dd] bg-[#fbfcf9] p-5 shadow-[0_8px_24px_rgba(42,67,52,0.03)] transition hover:-translate-y-0.5 hover:border-[#b8d0bb] hover:shadow-[0_14px_30px_rgba(42,67,52,0.08)]"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${accent}`}><Icon size={19} strokeWidth={1.8} /></span><ArrowUpRight size={16} className="text-[#a4b0a7]" /></div><p className="mt-5 text-3xl font-semibold tracking-[-0.04em] text-[#18352b]">{value}</p><p className="mt-1 text-sm font-semibold text-[#53685d]">{label}</p><p className="mt-2 text-xs text-[#98a49c]">{detail}</p></Link>;
}

function EmptyState({ label }: { label: string }) { return <div className="flex min-h-[130px] items-center justify-center rounded-xl border border-dashed border-[#d9e2d9] bg-[#fdfdfb] px-5 text-center text-sm text-[#91a098]">{label}</div>; }

export default function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { adminApi.dashboard().then(setData).catch((value) => setError(value instanceof Error ? value.message : "Impossible de charger le tableau de bord")); }, []);
  const products = data?.products ?? [];
  const orders = data?.orders ?? [];
  const reviews = data?.reviews ?? [];
  const notifications = data?.notifications ?? [];
  const pendingOrders = orders.filter((order) => order.status === "en attente").length;
  const approvedReviews = reviews.filter((review) => review.is_approved).length;

  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm capitalize text-[#7d8d83]">{today}</p><h2 className="mt-1 font-serif text-3xl text-[#18352b]">Bonjour</h2><p className="mt-2 text-sm text-[#7b8a81]">Voici ce qui se passe dans votre atelier aujourd’hui.</p></div><div className={`flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold ${data?.configured ? "border-[#dbe7dc] bg-[#eff7ef] text-[#3f7551]" : "border-[#e8d8bc] bg-[#fff9ee] text-[#8c6436]"}`}><span className={`h-2 w-2 rounded-full ${data?.configured ? "bg-[#5b9a6b]" : "bg-[#c48752]"}`} /> {data?.configured ? "Données synchronisées" : "Connexion à vérifier"}</div></div>
    {error && <div className="rounded-xl border border-[#edcfc4] bg-[#fff5f1] px-4 py-3 text-sm text-[#a64f3b]">{error}</div>}
    {data?.fromCache && <div className="rounded-2xl border border-[#e8d8bc] bg-[#fff9ee] px-5 py-4 text-sm text-[#8c6436]">Données du {data.cachedAt ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(data.cachedAt)) : "dernier chargement"} — en attente de connexion.</div>}
    {!data?.configured && <div className="rounded-2xl border border-[#e8d8bc] bg-[#fff9ee] px-5 py-4"><p className="text-sm font-bold text-[#8c6436]">Connexion aux données à finaliser</p><p className="mt-1 text-sm leading-6 text-[#a17e52]">Supabase n’est pas encore configuré sur cet environnement. Les indicateurs restent vides pour éviter toute donnée fictive.</p></div>}
    <div id="analytics" className="grid gap-4 scroll-mt-28 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Commandes en attente" value={data ? String(pendingOrders) : "—"} detail="Sur les dernières commandes" icon={Clock3} accent="bg-[#f7ead6] text-[#a17745]" to="/commandes" /><StatCard label="Produits en catalogue" value={data ? String(products.length) : "—"} detail="Produits enregistrés" icon={Package} accent="bg-[#e3f0e4] text-[#3f8054]" to="/produits" /><StatCard label="Avis approuvés" value={data ? String(approvedReviews) : "—"} detail="Sur les avis chargés" icon={Star} accent="bg-[#efe4f2] text-[#80608a]" to="/avis" /><StatCard label="Analytics GA4" value={data?.analyticsAvailable ? "Actif" : "—"} detail={data?.analyticsAvailable ? "Données disponibles" : "Statistiques non disponibles"} icon={TrendingUp} accent="bg-[#e3ebf4] text-[#547696]" to="/dashboard#analytics" /></div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_1fr]">
      <section className="rounded-2xl border border-[#dfe6dd] bg-[#fbfcf9] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#a17745]">Flux récent</p><h3 className="mt-1 font-serif text-2xl text-[#18352b]">Dernières commandes</h3></div><ShoppingBag size={20} className="text-[#80968a]" /></div>{orders.length ? <div className="space-y-1">{orders.slice(0, 5).map((order: Order) => <div key={order.id} className="flex items-center justify-between gap-4 border-t border-[#e8ede7] py-4"><div className="flex min-w-0 items-center gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#eaf1ea] text-[#4a805a]"><ShoppingBag size={15} /></span><div className="min-w-0"><p className="truncate text-sm font-bold text-[#355246]">{order.customer_name || `Commande #${String(order.id).slice(0, 7)}`}</p><p className="mt-1 text-xs text-[#99a49c]">{formatDate(order.created_at)}</p></div></div><div className="text-right"><p className="text-sm font-bold text-[#365347]">{money(order.total)}</p><span className="mt-1 inline-flex items-center gap-1 text-[11px] font-semibold text-[#7f9086]"><CheckCircle2 size={12} /> {order.status || "Statut inconnu"}</span></div></div>)}</div> : <EmptyState label="Aucune commande récente dans la base." />}</section>
      <section className="rounded-2xl border border-[#dfe6dd] bg-[#fbfcf9] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#a17745]">Atelier</p><h3 className="mt-1 font-serif text-2xl text-[#18352b]">État du catalogue</h3></div><Package size={20} className="text-[#80968a]" /></div>{products.length ? <div className="space-y-1">{products.slice(0, 5).map((product: Product) => <div key={product.id} className="flex items-center justify-between gap-3 border-t border-[#e8ede7] py-4"><div className="min-w-0"><p className="truncate text-sm font-bold text-[#355246]">{product.name || "Produit sans nom"}</p><p className="mt-1 text-xs text-[#99a49c]">Stock : {typeof product.stock === "number" ? product.stock : "non renseigné"}</p></div><span className="text-sm font-bold text-[#a17745]">{money(product.price)}</span></div>)}</div> : <EmptyState label="Aucun produit disponible dans la base." />}</section>
    </div>
    <section id="notifications" className="rounded-2xl border border-[#dfe6dd] bg-[#fbfcf9] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#a17745]">Notifications</p><h3 className="mt-1 font-serif text-2xl text-[#18352b]">Activité récente</h3></div><Clock3 size={20} className="text-[#80968a]" /></div>{notifications.length ? <div className="grid gap-3 md:grid-cols-3">{notifications.map((item, index) => { const notification = item as { order_id?: string; created_at?: string }; return <div key={notification.order_id ?? index} className="rounded-xl border border-[#e8ede7] bg-[#fdfdfb] p-4"><p className="text-sm font-bold text-[#365347]">Nouvelle commande</p><p className="mt-1 text-xs text-[#8b9a90]">#{String(notification.order_id ?? "").slice(0, 8) ?? "—"}</p><p className="mt-3 text-xs text-[#a17745]">{formatDate(notification.created_at)}</p></div>; })}</div> : <EmptyState label="Aucune notification récente dans la base." />}</section>
    <section className="rounded-2xl border border-[#dfe6dd] bg-[#fbfcf9] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.17em] text-[#a17745]">Retours clients</p><h3 className="mt-1 font-serif text-2xl text-[#18352b]">Derniers avis</h3></div><Star size={20} className="text-[#80968a]" /></div>{reviews.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{reviews.slice(0, 3).map((review: Review) => <div key={review.id} className="rounded-xl border border-[#e8ede7] bg-[#fdfdfb] p-4"><div className="flex justify-between"><span className="text-[#b38348]">{"★".repeat(Math.min(5, Math.max(0, review.rating ?? 0)))}</span><span className="text-xs text-[#9ca79f]">{formatDate(review.created_at)}</span></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-[#5e7065]">{review.comment || "Avis sans commentaire"}</p><p className="mt-3 text-xs font-bold text-[#365347]">{review.author_name || "Client anonyme"}</p></div>)}</div> : <EmptyState label="Aucun avis récent dans la base." />}</section>
  </div>;
}
