create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists product_images_product_position_idx
  on public.product_images(product_id, position);

create table if not exists public.product_available_colors (
  product_id bigint not null references public.products(id) on delete cascade,
  color text not null,
  created_at timestamptz not null default now(),
  primary key (product_id, color)
);
